esphome:
  name: batteryesp

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
 - platform: esphome
   password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  #manual_ip:
  #  static_ip: 10.0.16.40
  #  gateway: 10.0.16.1
  #  subnet: 255.255.255.0

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "BatteryESP WiFi Strength"
    update_interval: 480s

  - platform: adc
    pin: GPIO17
    name: "Battery Voltage"
    update_interval: 30s
    filters:
      - multiply: 13.15

binary_sensor:
  - platform: status
    name: "BatteryESP Status"
