esphome:
  name: bedrgb
  friendly_name: Bed RGB
  area: Caleb's Room

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
 - platform: esphome
   password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 10.15.16.17
    gateway: 10.15.16.1
    subnet: 255.255.255.0

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 480s

binary_sensor:
  - platform: status
    name: "Status"

# Example configuration entry
light:
  - platform: rgb
    name: "Head of Bed"
    red: headred
    green: headgreen
    blue: headblue
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - random:
      - random:
          name: "Fast Random"
          transition_length: 1s
          update_interval: 2s
      - flicker:

  - platform: rgb
    name: "Foot of Bed"
    red: foodred
    green: footgreen
    blue: footblue
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - random:
      - random:
          name: "Fast Random"
          transition_length: 1s
          update_interval: 2s
      - flicker:

output:
  - platform: esp8266_pwm
    id: headred
    pin: D3
    inverted: true

  - platform: esp8266_pwm
    id: headgreen
    pin: D4
    inverted: true
    max_power: 30%

  - platform: esp8266_pwm
    id: headblue
    pin: D5
    inverted: true
    max_power: 20%

  - platform: esp8266_pwm
    id: foodred
    pin: D0
    inverted: true

  - platform: esp8266_pwm
    id: footgreen
    pin: D1
    inverted: true
    max_power: 30%

  - platform: esp8266_pwm
    id: footblue
    pin: D2
    inverted: true
    max_power: 20%
