esphome:
  name: bedroomwall

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 10.0.16.19
    gateway: 10.0.16.1
    subnet: 255.255.255.0

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "BedroomWall WiFi Strength"
    update_interval: 480s

binary_sensor:
  - platform: status
    name: "BedroomWall Status"

  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: true
    name: "Bedroom Switch"