esphome:
  name: bedmotionsense
  friendly_name: BedSense
  area: Caleb's Room

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
 - platform: esphome
   password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 10.15.16.18
    gateway: 10.15.16.1
    subnet: 255.255.255.0

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 480s

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    pin: D2
    name: "Motion"
    device_class: motion