esphome:
  name: cabinetesp

esp8266:
  board: esp12e
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
 - platform: esphome
   password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 10.0.16.15
    gateway: 10.0.16.1
    subnet: 255.255.255.0

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "CabinetESP WiFi Strength"
    update_interval: 480s

binary_sensor:
  - platform: status
    name: "CabinetESP Status"

# Example configuration entry
light:
  - platform: monochromatic
    name: "Cabinet Lights"
    output: output_component1
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: 5