esphome:
  name: testesp3

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
 - platform: esphome
   password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  #manual_ip:
  #  static_ip: 10.0.16.40
  #  gateway: 10.0.16.1
  #  subnet: 255.255.255.0
  output_power: 18

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "testesp3 WiFi Strength"
    update_interval: 480s

binary_sensor:
  - platform: status
    name: "testesp3 Status"


light:
  - platform: rgb
    name: "RGB TEST3 Lights"
    red: output_component1
    green: output_component2
    blue: output_component3
    effects: 
      - random:
          name: "Fast Random"
          transition_length: 1s
          update_interval: 2s
  - platform: monochromatic
    name: "Red3"
    output: output_componentred
  - platform: monochromatic
    name: "Green3"
    output: output_componentgreen

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    max_power: 80%
    pin: 12
    inverted: true

  - platform: esp8266_pwm
    id: output_component2
    max_power: 80%
    pin: 13
    inverted: true

  - platform: esp8266_pwm
    id: output_component3
    max_power: 80%
    pin: 14
    inverted: true

  - platform: esp8266_pwm
    id: output_componentred
    max_power: 80%
    pin: 4
    inverted: true

  - platform: esp8266_pwm
    id: output_componentgreen
    max_power: 80%
    pin: 5
    inverted: true