esphome:
  name: workbench
  friendly_name: Workbench
  area: Playroom

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
 - platform: esphome
   password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 10.15.16.21
    gateway: 10.15.16.1
    subnet: 255.255.255.0

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 480s

binary_sensor:
  - platform: status
    name: "Status"

output:
  - platform: esp8266_pwm
    pin: D0
    frequency: 20000 Hz
    id: pwm_output

fan:
  - platform: speed
    output: pwm_output
    name: "Cabinet Fan"